version: "3.3"

services:
  db:
    container_name: "sql_test_db"
    image: "mdillon/postgis:10"
    volumes:
      - "./sql:/sql"
    env_file:
      - "env/local/.env"
    ports:
      - "5438:5432"
